package pl.isa.carservice.entity;

import lombok.Getter;

@Getter
public enum CarName {
    AUDI("Audi"),
    BMW("BMW"),
    CITROEN("Citroën"),
    FIAT("Fiat"),
    MERCEDES_BENZ("Mercedes-Benz"),
    OPEL("Opel"),
    RENAULT("Renault"),
    VW("Volkswagen"),
    ACURA("Acura"),
    ALFA_ROMEO("Alfa-Romeo"),
    BENTLEY("Bentley"),
    BUICK("Buick"),
    CADILLAC("Cadillac"),
    CHEVROLET("Chevrolet"),
    CHRYSLER("Chrysler"),
    DACIA("Dacia"),
    DAEWOO("Daewoo"),
    DAF("Daf"),
    DAIHATSU("Daihatsu"),
    DODGE("Dodge"),
    FERRARI("Ferrari"),
    FORD("Ford"),
    FSO("Fso"),
    HONDA("Honda"),
    HUMMER("Hummer"),
    HYUNDAI("Hyundai"),
    INFINITI("Infiniti"),
    ISUZU("Isuzu"),
    IVECO("Iveco"),
    JAGUAR("Jaguar"),
    JEEP("Jeep"),
    KIA("Kia"),
    LADA("Lada"),
    LAMBORGHINI("Lamborghini"),
    LANCIA("Lancia"),
    LAND_ROVER("Land Rover"),
    LDV("Ldv"),
    LEXUS("Lexus"),
    LINCOLN("Lincoln"),
    MAHINDRA("Mahindra"),
    MAN("MAN"),
    MASERATI("Maserati"),
    MAYBACH("Maybach"),
    MAZDA("Mazda"),
    MERCURY("Mercury"),
    MINI("Mini"),
    MITSUBISHI("Mitsubishi"),
    NISSAN("Nissan"),
    OLDSMOBILE("Oldsmobile"),
    PEUGEOT("Peugeot"),
    PLYMOUTH("Plymouth"),
    PONTIAC("Pontiac"),
    PORSCHE("Porsche"),
    RENAULT_TRUCKS("Renault Trucks"),
    ROLLS_ROYCE("Rolls-Royce"),
    ROVER("Rover"),
    SAAB("Saab"),
    SEAT("Seat"),
    SKODA("Skoda"),
    SMART("Smart"),
    SSANGYONG("Ssangyong"),
    STEYR("Steyr"),
    SUBARU("Subaru"),
    SUZUKI("Suzuki"),
    TALBOT("Talbot"),
    TATA("Tata"),
    TESLA("Tesla"),
    TOYOTA("Toyota"),
    VOLVO("Volvo"),
    INNA("Inna");

    private final String nameOfCar;

    CarName(String nameOfCar) {
        this.nameOfCar = nameOfCar;
    }
}